### ISSUE TITLE
[Bug]: Instant Crash Apon Start Up

### ISSUE THREAD

**Issue by KaidKM3** [Mrbysco/NeoAuth#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.3.12

### Minecraft version

1.20.1

### Mod version

1.0.0

### Java version

Java 21, Java 17, Java 8

### Issue Description

Steps to what happened in the crashes that happen consistently

Stage 1, Startup (Fine For Now)

Stage 2, Minecraft Screen Appears

Stage 3, Right as the screen appears for Minecraft, It instantly freezes

Stage 4, wait a couple moments,

Stage 5, Errorless Crash.

Probable Cause - Not Using NeoForge, And Using Forge Instead.

### Additional Information

[latest.log](https://github.com/user-attachments/files/18160629/latest.log)

**Comment by Mrbysco** [comment]
Can you reproduce this issue with just NeoAuth in a forge instance? (the 1.20 version is built against Forge so it shouldn't be an issue)

**Comment by Mrbysco** [comment]
Going off the log something is going wrong in your instance where a lot of modded classes can't be located

**Comment by KaidKM3** [comment]
i put it in a pack of its own (no other mods installed), and it still crashed

And it mentioned something about Graphical Driver Issues, Which ive never gotten from Forge before

Raw
"
[17Dec2024 08:48:19.294] [main/INFO] [EARLYDISPLAY/]: If this message is the only thing at the bottom of your log before a crash, you probably have a driver issue.
Possible solutions:
A) Make sure Minecraft is set to prefer high performance graphics in the OS and/or driver control panel
B) Check for driver updates on the graphics brand's website
C) Try reinstalling your graphics drivers
D) If still not working after trying all of the above, ask for further help on the Forge forums or Discord
"
Other Modpacks start up fine and do not mention this issue.

Just in case it is
Driver Version 31.0.15.5212


[latest.log](https://github.com/user-attachments/files/18166389/latest.log)

Edit | I Also did another test, For Neoforge. and it also crashed instantly. So i dont know what happened but the mod will not work at all.
Heres the log for Neoforge

[latest.log](https://github.com/user-attachments/files/18166521/latest.log) | NEOFORGE VERSION

**Comment by Mrbysco** [comment]
Uploaded a new jar with the fixed refmap https://www.curseforge.com/minecraft/mc-mods/neoauth/files/5998808 Please try that one instead

**Comment by KaidKM3** [comment]
~The mod works now, i am no longer crashing. (thank)~

Nevermind Apon Opening Multiplayer it instantly crashed

This time its giving an title onClick event crash.


[latest.log](https://github.com/user-attachments/files/18168442/latest.log)

**Comment by Mrbysco** [comment]
A new version is being generated and uploaded

**Comment by Mrbysco** [comment]
Should be fixed in https://www.curseforge.com/minecraft/mc-mods/neoauth/files/5999179

**Comment by KaidKM3** [comment]
Sorry for absence, Its still crashing

Edit: Same Thing is happening. like earlier today, Onclick event handler is crashing the game when opening up multiplayer screen.

[latest.log](https://github.com/user-attachments/files/18173568/latest.log)

**Comment by Mrbysco** [comment]
I was unable to reproduce it in a new build

**Comment by Mrbysco** [comment]
I'll try again tomorrow
